# Generated by Django 5.0.4 on 2024-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseCode', models.CharField(max_length=500)),
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
