# Generated by Django 5.0.4 on 2024-05-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='CourseProf',
            field=models.CharField(default='Joe Bob', max_length=500),
            preserve_default=False,
        ),
    ]
