# Generated by Django 5.0.4 on 2024-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_courses_coursedesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='CourseLevel',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='CourseProgram',
            field=models.CharField(default='CISC', max_length=4),
            preserve_default=False,
        ),
    ]
