# Generated by Django 5.0.4 on 2024-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewDate', models.DateTimeField(max_length=500)),
                ('ReviewScore', models.IntegerField()),
                ('ReviewDifficulty', models.IntegerField()),
                ('ReviewContent', models.CharField(max_length=2000)),
            ],
        ),
    ]
