# Generated by Django 5.0.4 on 2024-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='ReviewCourse',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
