# Generated by Django 5.0.4 on 2024-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Username', models.CharField(max_length=500)),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
    ]
